import React, { useCallback, useEffect, useState } from 'react';
import { ClipboardCheck, Plus, Save, Send, CheckCircle2, XCircle } from 'lucide-react';
import { stockCountService, StockCountLine, StockCountSession } from '../services/stockCountService';

const labels: Record<string,string> = { draft:'Nháp', submitted:'Chờ duyệt', approved:'Đã duyệt', rejected:'Từ chối' };

const StockCountPage: React.FC = () => {
  const [sessions,setSessions]=useState<StockCountSession[]>([]); const [selectedId,setSelectedId]=useState('');
  const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [notes,setNotes]=useState('');
  const [reviewNotes,setReviewNotes]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<{type:'success'|'error';text:string}|null>(null);
  const selected=sessions.find(s=>s.id===selectedId);
  const load=useCallback(async(preferred?:string)=>{setLoading(true);try{const data=await stockCountService.list();setSessions(data);setSelectedId(current=>preferred||current||data[0]?.id||'');}catch(e){setMessage({type:'error',text:e instanceof Error?e.message:'Không tải được phiên kiểm kê'});}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const run=async<T,>(action:()=>Promise<T>,success:string,preferred?:(result:T)=>string|undefined)=>{setBusy(true);setMessage(null);try{const result=await action();setMessage({type:'success',text:success});await load(preferred?.(result)||selectedId)}catch(e){setMessage({type:'error',text:e instanceof Error?e.message:'Có lỗi xảy ra'});}finally{setBusy(false)}};
  const create=()=>run(()=>stockCountService.create(date,notes),'Đã chốt snapshot tồn sổ cho phiên kiểm kê',id=>id);
  const updateLine=(id:string,patch:Partial<StockCountLine>)=>setSessions(prev=>prev.map(s=>s.id!==selectedId?s:{...s,lines:s.lines.map(l=>l.id===id?{...l,...patch}:l)}));
  const save=()=>selected&&run(()=>stockCountService.saveLines(selected.id,selected.lines),'Đã lưu tồn thực tế và giải trình');
  const submit=()=>selected&&run(async()=>{await stockCountService.saveLines(selected.id,selected.lines);await stockCountService.submit(selected.id)},'Đã gửi phiên kiểm kê để duyệt');
  const review=(action:'approve'|'reject')=>selected&&run(()=>stockCountService.review(selected.id,action,reviewNotes),action==='approve'?'Đã duyệt và sinh phiếu điều chỉnh liên kết':'Đã từ chối phiên kiểm kê');
  return <div className="min-h-screen bg-gray-50 p-4 dark:bg-gray-950 sm:p-6"><div className="mx-auto max-w-7xl space-y-5">
    <header className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900"><div className="flex items-center gap-3"><ClipboardCheck className="h-7 w-7 text-blue-600"/><div><h1 className="text-2xl font-bold text-gray-900 dark:text-white">Phiên kiểm kê</h1><p className="text-sm text-gray-500">Snapshot tồn sổ → nhập tồn thực tế → giải trình → duyệt → điều chỉnh.</p></div></div></header>
    {message&&<div role="alert" className={`rounded-xl border p-3 text-sm ${message.type==='success'?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-red-200 bg-red-50 text-red-800'}`}>{message.text}</div>}
    <section className="grid gap-4 rounded-2xl border border-gray-100 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-900 md:grid-cols-[180px_1fr_auto]">
      <label className="text-sm text-gray-600 dark:text-gray-300">Ngày kiểm kê<input aria-label="Ngày kiểm kê" type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 w-full rounded-lg border p-2 dark:border-gray-700 dark:bg-gray-800"/></label>
      <label className="text-sm text-gray-600 dark:text-gray-300">Ghi chú<input aria-label="Ghi chú phiên kiểm kê" value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1 w-full rounded-lg border p-2 dark:border-gray-700 dark:bg-gray-800" placeholder="Ví dụ: kiểm kê cuối tháng"/></label>
      <button onClick={create} disabled={busy} className="self-end rounded-lg bg-blue-600 px-4 py-2 font-medium text-white disabled:opacity-50"><Plus className="mr-2 inline h-4 w-4"/>Tạo và chốt tồn sổ</button>
    </section>
    <div className="grid gap-5 lg:grid-cols-[280px_1fr]"><aside className="rounded-2xl border bg-white p-3 dark:border-gray-800 dark:bg-gray-900"><h2 className="px-2 py-2 font-semibold dark:text-white">Các phiên kiểm kê</h2>{loading?<p className="p-3 text-sm text-gray-500">Đang tải...</p>:sessions.length===0?<p className="p-3 text-sm text-gray-500">Chưa có phiên nào</p>:sessions.map(s=><button key={s.id} onClick={()=>setSelectedId(s.id)} className={`mb-2 w-full rounded-xl border p-3 text-left ${s.id===selectedId?'border-blue-500 bg-blue-50 dark:bg-blue-950/30':'border-gray-200 dark:border-gray-700'}`}><div className="font-medium dark:text-white">{new Date(s.count_date).toLocaleDateString('vi-VN')}</div><div className="mt-1 text-xs text-gray-500">{labels[s.status]} · {s.lines.length} sản phẩm</div></button>)}</aside>
      <main className="overflow-hidden rounded-2xl border bg-white dark:border-gray-800 dark:bg-gray-900">{!selected?<div className="p-10 text-center text-gray-500">Chọn hoặc tạo một phiên kiểm kê</div>:<><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4 dark:border-gray-800"><div><h2 className="font-semibold dark:text-white">Kiểm kê ngày {new Date(selected.count_date).toLocaleDateString('vi-VN')}</h2><span className="text-sm text-gray-500">Trạng thái: {labels[selected.status]}</span></div>{selected.status==='draft'&&<div className="flex gap-2"><button onClick={save} disabled={busy} className="rounded-lg border px-3 py-2 text-sm dark:border-gray-700 dark:text-white"><Save className="mr-1 inline h-4 w-4"/>Lưu</button><button onClick={submit} disabled={busy} className="rounded-lg bg-blue-600 px-3 py-2 text-sm text-white"><Send className="mr-1 inline h-4 w-4"/>Gửi duyệt</button></div>}</div>
      <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500 dark:bg-gray-800"><tr><th className="p-3">Sản phẩm</th><th className="p-3 text-right">Tồn sổ chốt</th><th className="p-3 text-right">Tồn thực tế</th><th className="p-3 text-right">Chênh lệch</th><th className="p-3">Giải trình</th><th className="p-3">Phiếu điều chỉnh</th></tr></thead><tbody className="divide-y dark:divide-gray-800">{selected.lines.map(line=>{const variance=line.counted_quantity===null?null:Number(line.counted_quantity)-Number(line.book_quantity);return <tr key={line.id}><td className="p-3"><div className="font-medium dark:text-white">{line.product?.name}</div><div className="text-xs text-gray-500">{line.product?.business_code} · {line.unit}</div></td><td className="p-3 text-right dark:text-white">{Number(line.book_quantity).toLocaleString('vi-VN')}</td><td className="p-3 text-right"><input aria-label={`Tồn thực tế ${line.product?.business_code}`} type="number" min="0" step="0.001" disabled={selected.status!=='draft'} value={line.counted_quantity??''} onChange={e=>updateLine(line.id,{counted_quantity:e.target.value===''?null:Number(e.target.value)})} className="w-28 rounded-lg border p-2 text-right dark:border-gray-700 dark:bg-gray-800 dark:text-white"/></td><td className={`p-3 text-right font-semibold ${variance===0?'text-gray-500':variance&&variance>0?'text-emerald-600':'text-rose-600'}`}>{variance===null?'—':variance.toLocaleString('vi-VN')}</td><td className="p-3"><input aria-label={`Giải trình ${line.product?.business_code}`} disabled={selected.status!=='draft'} value={line.explanation||''} onChange={e=>updateLine(line.id,{explanation:e.target.value})} className="w-full min-w-48 rounded-lg border p-2 dark:border-gray-700 dark:bg-gray-800 dark:text-white" placeholder={variance&&variance!==0?'Bắt buộc khi có lệch':'Không có lệch'}/></td><td className="p-3 text-xs text-gray-500">{line.adjustment_record_id||'—'}</td></tr>})}</tbody></table></div>
      {selected.status==='submitted'&&<div className="flex flex-wrap items-end gap-3 border-t p-4 dark:border-gray-800"><label className="min-w-64 flex-1 text-sm text-gray-600 dark:text-gray-300">Ý kiến duyệt<input aria-label="Ý kiến duyệt" value={reviewNotes} onChange={e=>setReviewNotes(e.target.value)} className="mt-1 w-full rounded-lg border p-2 dark:border-gray-700 dark:bg-gray-800"/></label><button onClick={()=>review('reject')} disabled={busy} className="rounded-lg border border-red-300 px-4 py-2 text-red-700"><XCircle className="mr-1 inline h-4 w-4"/>Từ chối</button><button onClick={()=>review('approve')} disabled={busy} className="rounded-lg bg-emerald-600 px-4 py-2 text-white"><CheckCircle2 className="mr-1 inline h-4 w-4"/>Duyệt & điều chỉnh</button></div>}</>}</main></div>
  </div></div>;
};
export default StockCountPage;
