import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { FlaskConical, Save, Eye, Plus, Trash2, Undo2, Check, AlertCircle, X, Search, ExternalLink, Columns } from 'lucide-react';
import { useAuthContext } from '@superapp/iam';

const genId = () => crypto.randomUUID?.()?.slice(0, 8) || Math.random().toString(36).slice(2, 10);

interface FieldDef {
  name: string;
  label: string;
  type: 'string' | 'number' | 'boolean';
  required?: boolean;
}

const SCHEMA: Record<string, FieldDef[]> = {
  inventory_records: [
    { name: 'product_id', label: 'Mã SP', type: 'string', required: true },
    { name: 'product_code', label: 'Mã Code', type: 'string' },
    { name: 'product_name', label: 'Tên SP', type: 'string' },
    { name: 'warehouse', label: 'Kho', type: 'string' },
    { name: 'input_date', label: 'Ngày nhập', type: 'string' },
    { name: 'quantity', label: 'Số lượng', type: 'number', required: true },
    { name: 'batch_number', label: 'Số lô', type: 'string' },
    { name: 'unit', label: 'ĐVT', type: 'string' },
    { name: 'notes', label: 'Ghi chú', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
  ],
  products: [
    { name: 'name', label: 'Tên SP', type: 'string', required: true },
    { name: 'code', label: 'Mã SP', type: 'string' },
    { name: 'category', label: 'Danh mục', type: 'string' },
    { name: 'price', label: 'Đơn giá', type: 'number', required: true },
    { name: 'unit', label: 'ĐVT', type: 'string' },
    { name: 'stock', label: 'Tồn kho', type: 'number' },
    { name: 'description', label: 'Mô tả', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
    { name: 'is_active', label: 'Kích hoạt', type: 'boolean' },
  ],
  sales_records: [
    { name: 'product_id', label: 'SP ID', type: 'string', required: true },
    { name: 'product_code', label: 'Mã SP', type: 'string' },
    { name: 'quantity', label: 'Số lượng', type: 'number', required: true },
    { name: 'total', label: 'Thành tiền', type: 'number' },
    { name: 'customer_id', label: 'KH ID', type: 'string' },
    { name: 'sale_date', label: 'Ngày bán', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
  ],
  companies: [
    { name: 'name', label: 'Tên cty', type: 'string', required: true },
    { name: 'address', label: 'Địa chỉ', type: 'string' },
    { name: 'phone', label: 'SĐT', type: 'string' },
    { name: 'email', label: 'Email', type: 'string' },
    { name: 'is_active', label: 'Kích hoạt', type: 'boolean' },
  ],
  branches: [
    { name: 'name', label: 'Tên CN', type: 'string', required: true },
    { name: 'code', label: 'Mã CN', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
    { name: 'address', label: 'Địa chỉ', type: 'string' },
    { name: 'phone', label: 'SĐT', type: 'string' },
    { name: 'is_active', label: 'Kích hoạt', type: 'boolean' },
  ],
  users: [
    { name: 'email', label: 'Email', type: 'string', required: true },
    { name: 'full_name', label: 'Họ tên', type: 'string', required: true },
    { name: 'role', label: 'Vai trò', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
    { name: 'branch_id', label: 'CN ID', type: 'string' },
    { name: 'is_active', label: 'Kích hoạt', type: 'boolean' },
  ],
  customers: [
    { name: 'full_name', label: 'Tên KH', type: 'string', required: true },
    { name: 'customer_code', label: 'Mã KH', type: 'string' },
    { name: 'phone', label: 'SĐT', type: 'string' },
    { name: 'email', label: 'Email', type: 'string' },
    { name: 'total_balance', label: 'Số dư', type: 'number' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
    { name: 'is_active', label: 'Kích hoạt', type: 'boolean' },
  ],
  transactions: [
    { name: 'amount', label: 'Số tiền', type: 'number', required: true },
    { name: 'description', label: 'Mô tả', type: 'string' },
    { name: 'transaction_type_id', label: 'Loại GD', type: 'string' },
    { name: 'customer_id', label: 'KH ID', type: 'string' },
    { name: 'customer_name', label: 'Tên KH', type: 'string' },
    { name: 'bank_account_id', label: 'TK NH ID', type: 'string' },
    { name: 'transaction_date', label: 'Ngày GD', type: 'string' },
    { name: 'status', label: 'Trạng thái', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
    { name: 'branch_id', label: 'CN ID', type: 'string' },
  ],
  transaction_types: [
    { name: 'name', label: 'Tên loại', type: 'string', required: true },
    { name: 'math_factor', label: 'Hệ số', type: 'number' },
    { name: 'impact_type', label: 'Tác động', type: 'string' },
    { name: 'color', label: 'Màu', type: 'string' },
    { name: 'is_active', label: 'Kích hoạt', type: 'boolean' },
  ],
  bank_accounts: [
    { name: 'account_name', label: 'Tên TK', type: 'string', required: true },
    { name: 'account_number', label: 'Số TK', type: 'string' },
    { name: 'bank_name', label: 'Ngân hàng', type: 'string' },
    { name: 'balance', label: 'Số dư', type: 'number' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
    { name: 'is_active', label: 'Kích hoạt', type: 'boolean' },
  ],
  departments: [
    { name: 'name', label: 'Tên PB', type: 'string', required: true },
    { name: 'code', label: 'Mã PB', type: 'string' },
    { name: 'manager_id', label: 'Trưởng PB ID', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
  ],
  employees: [
    { name: 'full_name', label: 'Họ tên', type: 'string', required: true },
    { name: 'email', label: 'Email', type: 'string' },
    { name: 'phone', label: 'SĐT', type: 'string' },
    { name: 'department_id', label: 'PB ID', type: 'string' },
    { name: 'position', label: 'Chức vụ', type: 'string' },
    { name: 'salary', label: 'Lương', type: 'number' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
    { name: 'branch_id', label: 'CN ID', type: 'string' },
    { name: 'is_active', label: 'Kích hoạt', type: 'boolean' },
  ],
  shifts: [
    { name: 'name', label: 'Tên ca', type: 'string', required: true },
    { name: 'start_time', label: 'Bắt đầu', type: 'string' },
    { name: 'end_time', label: 'Kết thúc', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
  ],
  leave_requests: [
    { name: 'employee_id', label: 'NV ID', type: 'string' },
    { name: 'leave_type', label: 'Loại nghỉ', type: 'string' },
    { name: 'start_date', label: 'Ngày bắt đầu', type: 'string' },
    { name: 'end_date', label: 'Ngày kết thúc', type: 'string' },
    { name: 'status', label: 'Trạng thái', type: 'string' },
    { name: 'reason', label: 'Lý do', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
  ],
  employee_shifts: [
    { name: 'employee_id', label: 'NV ID', type: 'string' },
    { name: 'shift_id', label: 'Ca ID', type: 'string' },
    { name: 'date', label: 'Ngày', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
  ],
  attendance_logs: [
    { name: 'employee_id', label: 'NV ID', type: 'string' },
    { name: 'date', label: 'Ngày', type: 'string' },
    { name: 'check_in', label: 'Check-in', type: 'string' },
    { name: 'check_out', label: 'Check-out', type: 'string' },
    { name: 'status', label: 'Trạng thái', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
  ],
  payrolls: [
    { name: 'employee_id', label: 'NV ID', type: 'string' },
    { name: 'month', label: 'Tháng', type: 'string' },
    { name: 'basic_salary', label: 'Lương CB', type: 'number' },
    { name: 'allowances', label: 'Phụ cấp', type: 'number' },
    { name: 'deductions', label: 'Khấu trừ', type: 'number' },
    { name: 'net_salary', label: 'Thực nhận', type: 'number' },
    { name: 'status', label: 'Trạng thái', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
  ],
  payroll_items: [
    { name: 'payroll_id', label: 'BL ID', type: 'string' },
    { name: 'item_type', label: 'Loại', type: 'string' },
    { name: 'label', label: 'Nhãn', type: 'string' },
    { name: 'amount', label: 'Số tiền', type: 'number' },
  ],
  special_outbound_records: [
    { name: 'product_code', label: 'Mã SP', type: 'string' },
    { name: 'output_date', label: 'Ngày xuất', type: 'string' },
    { name: 'quantity', label: 'Số lượng', type: 'number', required: true },
    { name: 'reason', label: 'Lý do', type: 'string' },
    { name: 'notes', label: 'Ghi chú', type: 'string' },
    { name: 'status', label: 'Trạng thái', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
  ],
  operation_tickets: [
    { name: 'title', label: 'Tiêu đề', type: 'string', required: true },
    { name: 'description', label: 'Mô tả', type: 'string' },
    { name: 'status', label: 'Trạng thái', type: 'string' },
    { name: 'priority', label: 'Ưu tiên', type: 'string' },
    { name: 'assigned_to', label: 'Giao cho', type: 'string' },
    { name: 'created_by', label: 'Người tạo', type: 'string' },
  ],
  operation_assets: [
    { name: 'name', label: 'Tên TS', type: 'string', required: true },
    { name: 'category', label: 'Loại', type: 'string' },
    { name: 'location', label: 'Vị trí', type: 'string' },
    { name: 'status', label: 'Trạng thái', type: 'string' },
    { name: 'price', label: 'Giá trị', type: 'number' },
  ],
  operation_consumables: [
    { name: 'name', label: 'Tên VT', type: 'string', required: true },
    { name: 'location', label: 'Vị trí', type: 'string' },
    { name: 'quantity', label: 'Số lượng', type: 'number', required: true },
    { name: 'unit', label: 'ĐVT', type: 'string' },
  ],
  operation_documents: [
    { name: 'title', label: 'Tiêu đề', type: 'string', required: true },
    { name: 'document_type', label: 'Loại VB', type: 'string' },
    { name: 'file_url', label: 'Đường dẫn', type: 'string' },
    { name: 'description', label: 'Mô tả', type: 'string' },
  ],
  operation_emergency_contacts: [
    { name: 'name', label: 'Tên LH', type: 'string', required: true },
    { name: 'phone', label: 'SĐT', type: 'string' },
    { name: 'category', label: 'Danh mục', type: 'string' },
    { name: 'notes', label: 'Ghi chú', type: 'string' },
  ],
  operation_training_courses: [
    { name: 'title', label: 'Tên khóa học', type: 'string', required: true },
    { name: 'description', label: 'Mô tả', type: 'string' },
    { name: 'category', label: 'DM', type: 'string' },
  ],
  operation_training_materials: [
    { name: 'course_id', label: 'KH ID', type: 'string' },
    { name: 'title', label: 'Tiêu đề', type: 'string', required: true },
    { name: 'material_type', label: 'Loại', type: 'string' },
    { name: 'order_index', label: 'Thứ tự', type: 'number' },
  ],
  operation_training_progress: [
    { name: 'course_id', label: 'KH ID', type: 'string' },
    { name: 'user_id', label: 'User ID', type: 'string' },
    { name: 'status', label: 'Trạng thái', type: 'string' },
    { name: 'score', label: 'Điểm', type: 'number' },
  ],
  operation_chat_groups: [
    { name: 'name', label: 'Tên nhóm', type: 'string', required: true },
    { name: 'description', label: 'Mô tả', type: 'string' },
  ],
  operation_chat_members: [
    { name: 'group_id', label: 'Nhóm ID', type: 'string' },
    { name: 'user_id', label: 'User ID', type: 'string' },
    { name: 'role', label: 'Vai trò', type: 'string' },
  ],
  operation_chat_messages: [
    { name: 'group_id', label: 'Nhóm ID', type: 'string' },
    { name: 'user_id', label: 'User ID', type: 'string' },
    { name: 'message', label: 'Nội dung', type: 'string', required: true },
  ],
  approval_workflows: [
    { name: 'name', label: 'Tên luồng', type: 'string', required: true },
    { name: 'steps', label: 'Số bước', type: 'number' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
    { name: 'is_active', label: 'Kích hoạt', type: 'boolean' },
  ],
  approval_logs: [
    { name: 'workflow_id', label: 'Luồng ID', type: 'string' },
    { name: 'record_type', label: 'Loại ghi', type: 'string' },
    { name: 'record_id', label: 'Ghi ID', type: 'string' },
    { name: 'approver_id', label: 'Duyệt ID', type: 'string' },
    { name: 'status', label: 'Trạng thái', type: 'string' },
    { name: 'comment', label: 'NX', type: 'string' },
    { name: 'company_id', label: 'Cty ID', type: 'string' },
  ],
};
