/* Auto-generated from docs/NEW-APP-TEMPLATE/. Do not edit manually. */
window.NEW_APP_TEMPLATES = {
  "AI-CONTEXT": "---\napp: <APP_NAME>\ndoc_type: AI-CONTEXT\n---\n\n# <APP_NAME> — AI Context\n\n## One-line summary\n\n<!-- What does this app do? -->\n\n## Read this first\n\n- `apps/<APP_NAME>/docs/OVERVIEW.md`\n- `apps/<APP_NAME>/docs/DATA-MODEL.md`\n- `apps/<APP_NAME>/docs/ROLES-PERMISSIONS.md`\n- `apps/<APP_NAME>/docs/CHANGELOG.md`\n\n## Common tasks\n\n| Task | Start here |\n|------|------------|\n| Add a page | `src/pages/` + `App.tsx` route |\n| Add a service | `src/services/<feature>Service.ts` |\n| Change DB query | service + `supabase/migrations/` |\n| Add permission | `src/types/UserRole.ts` |\n\n## Key gotchas\n\n- `id` columns are `text` with v4 UUID strings, not `uuid` type.\n- Always scope mutations by `company_id`.\n- Use `.maybeSingle()` for read-one queries.\n- No schema-per-tenant.\n",
  "API": "---\napp: <APP_NAME>\ndoc_type: API\n---\n\n# <APP_NAME> — API / Service Surface\n\n## Service modules\n\n- `src/services/<feature>Service.ts`\n\n## Conventions\n\n- Return `{ data, error }` shapes.\n- Normalize errors to Vietnamese user messages.\n- Inject `company_id` from `useCompany()`.\n\n## Backend\n\n- Supabase REST / RPC\n- `packages/api` Fastify (port 3001) for shared utilities\n",
  "ARCHITECTURE": "---\napp: <APP_NAME>\ndoc_type: ARCHITECTURE\n---\n\n# <APP_NAME> — Architecture\n\n## Directory layout\n\n```\napps/<APP_NAME>/\n├── src/\n│   ├── main.tsx\n│   ├── App.tsx\n│   ├── pages/\n│   ├── services/\n│   ├── components/\n│   ├── hooks/\n│   ├── types/\n│   └── utils/\n├── docs/\n└── package.json\n```\n\n## Shared packages used\n\n- `@superapp/iam`\n- `@superapp/shared-utils`\n- `@repo/ui`\n- `@superapp/theme`\n\n## Multi-tenancy\n\nAll data access is scoped by `company_id` / `branch_id`. RLS enforces isolation.\n\n## Build flow\n\n```bash\nnpx turbo run build --filter=<APP_NAME>\nnpx turbo run check-types --filter=<APP_NAME>\nnpx turbo run test --filter=<APP_NAME>\nnpx turbo run lint --filter=<APP_NAME>\n```\n",
  "CHANGELOG": "---\napp: <APP_NAME>\ndoc_type: CHANGELOG\n---\n\n# <APP_NAME> — Changelog\n\n## Unreleased\n\n- Initial app skeleton created from `docs/NEW-APP-TEMPLATE/`.\n",
  "CHECKLIST": "# New App Checklist\n\n- [ ] `apps/<app>/package.json` with React 18 + TypeScript 5.8\n- [ ] `apps/<app>/vite.config.ts` and `tsconfig.json`\n- [ ] `apps/<app>/src/main.tsx` wrapping `<AuthProvider>` and `<CompanyProvider>`\n- [ ] `apps/<app>/src/App.tsx` with routes\n- [ ] `apps/<app>/src/pages/` with at least a dashboard / list page\n- [ ] `apps/<app>/src/services/` with a `*Service.ts` using `createApiClient`\n- [ ] `apps/<app>/src/types/UserRole.ts` (or `src/utils/rbac.ts`) with roles & permissions\n- [ ] `apps/<app>/docs/` created with the 12 files from this template\n- [ ] `apps/<app>/.env.example` and Vercel project linked\n- [ ] Add app to root `README.md`, `AGENTS.md`, `turbo.json`, and GitHub Action deploy matrix\n- [ ] Run `npx turbo run check-types lint test build --filter=<app>`\n",
  "DATA-FLOW": "---\napp: <APP_NAME>\ndoc_type: DATA-FLOW\n---\n\n# <APP_NAME> — Data Flow\n\n1. User logs in via `@superapp/iam`.\n2. `CompanyProvider` resolves `company_id` / `branch_id`.\n3. Components call `src/services/<feature>Service.ts`.\n4. Service uses `createApiClient` → Supabase cloud.\n5. RLS validates `company_id` / `branch_id`.\n6. UI renders result; errors shown in Vietnamese.\n\n## Import / export\n\n- Export: table view → `xlsx` with Vietnamese headers.\n- Import: file → parser → validation → bulk insert with `company_id`.\n",
  "DATA-MODEL": "---\napp: <APP_NAME>\ndoc_type: DATA-MODEL\n---\n\n# <APP_NAME> — Data Model\n\n## Tenant scoping\n\n- `company_id` FK to `companies.id`\n- `branch_id` optional FK to `branches.id`\n- `id` columns should be `text` with v4 UUID strings (`crypto.randomUUID()`)\n\n## Core tables\n\n- `<app_name>_<entity>`\n- `companies`\n- `users`\n- `branches`\n\n## Agent notes\n\n- Use `.maybeSingle()` for reads that may return no row.\n- Always include `company_id` in `.insert()` / `.update()`.\n",
  "FLOWS": "---\napp: <APP_NAME>\ndoc_type: FLOWS\n---\n\n# <APP_NAME> — User Flows\n\n## Core flows\n\n- Dashboard overview\n- List → create → edit → delete\n- Import / export\n\n## Generic CRUD\n\n1. List view with search, sort, filters.\n2. Create/edit modal or page.\n3. Validation and submit to `<feature>Service.ts`.\n4. Toast confirmation; refresh list.\n",
  "OVERVIEW": "---\napp: <APP_NAME>\ndoc_type: OVERVIEW\n---\n\n# <APP_NAME> — Overview\n\n## Purpose\n\n<!-- One-line purpose -->\n\n- **Local port:** PORT\n- **Production domain:** `https://<APP_NAME>.appforyou.xyz`\n- **Vercel project:** `<APP_NAME>`\n\n## Tech stack\n\n- React 18 + TypeScript 5.8 + Vite 8\n- Tailwind CSS (Apple-inspired design tokens from `@superapp/theme`)\n- Supabase cloud (`peslmsctejmvkwzyohke`) via `@superapp/shared-utils` `createApiClient`\n- Shared auth / company context from `@superapp/iam`\n\n## Main pages\n\n- `Dashboard`\n- `Settings`\n\n## Main services\n\n- `<feature>Service.ts`\n\n## Related Supabase tables\n\n- `companies`\n- `users`\n- `branches`\n\n## Quick links\n\n- `apps/<APP_NAME>/docs/ARCHITECTURE.md`\n- `apps/<APP_NAME>/docs/DATA-MODEL.md`\n- `apps/<APP_NAME>/docs/API.md`\n- `apps/<APP_NAME>/docs/AI-CONTEXT.md`\n- `apps/<APP_NAME>/docs/CHANGELOG.md`\n",
  "PRD": "---\napp: <APP_NAME>\ndoc_type: PRD\n---\n\n# <APP_NAME> — Product Requirements\n\n## Problem\n\n<!-- What user problem does this app solve? -->\n\n## Goals\n\n- Mobile-first, Vietnamese UI.\n- Consistent with Superapp design/auth/RBAC.\n\n## In scope\n\n- Dashboard\n- CRUD flows\n- Reports / exports\n\n## Out of scope\n\n- Schema-per-tenant\n- New backend framework (use Supabase + `packages/api` Fastify)\n\n## User stories\n\n- As an admin, I can manage company users and settings.\n- As a staff user, I can perform operations within my permissions.\n\n## Non-functional requirements\n\n- Vietnamese-first labels\n- Responsive design\n- Friendly error messages\n",
  "README": "# New App Template\n\nThis folder is the canonical skeleton for a new Superapp Vite app. Copy the files into `apps/<new-app>/` and follow `CHECKLIST.md`.\n",
  "ROLES-PERMISSIONS": "---\napp: <APP_NAME>\ndoc_type: ROLES-PERMISSIONS\n---\n\n# <APP_NAME> — Roles & Permissions\n\n## User roles\n\n- `ADMIN_MASTER` (`admin_master`)\n- `ADMIN_COMPANY` (`admin_company`)\n- `STAFF` (`staff`)\n\n## Permissions\n\nDefine in `src/types/UserRole.ts` or `src/utils/rbac.ts`.\n\n## Enforcement\n\n- `hasPermission(user, Permission.XXX)` in UI.\n- Route/menu guards.\n- RLS is the final authority.\n",
  "RUNBOOK": "---\napp: <APP_NAME>\ndoc_type: RUNBOOK\n---\n\n# <APP_NAME> — Runbook\n\n## Local dev\n\n```bash\nnpx turbo run dev --filter=<APP_NAME>\n```\n\n## Build & test\n\n```bash\nnpx turbo run check-types --filter=<APP_NAME>\nnpx turbo run lint --filter=<APP_NAME>\nnpx turbo run test --filter=<APP_NAME>\nnpx turbo run build --filter=<APP_NAME>\n```\n\n## Deploy\n\n1. Push `origin/viet` → Vercel preview.\n2. Verify preview URL.\n3. Merge `viet` → `main` → production `https://<APP_NAME>.appforyou.xyz`.\n\n## Troubleshooting\n\n- `401` → check Supabase URL/key match.\n- `check-types` fails → ensure `tsconfig.json` uses `ESNext`/`bundler`.\n",
  "UI-UX": "---\napp: <APP_NAME>\ndoc_type: UI-UX\n---\n\n# <APP_NAME> — UI/UX Guide\n\n- Apple-inspired clean UI.\n- Dark mode via `@superapp/theme`.\n- Vietnamese-first labels.\n- Mobile-first responsive.\n- Toast feedback; no raw `alert()`.\n- Use `@repo/ui` `DataTable`, `Button`, modals.\n\nSee `apps/cashflow/docs/APPLE-HIG-UIUX-GUIDE.md` for full guidelines.\n"
};
