import { describe, it, expect } from 'vitest';

describe('Database Types', () => {
  it('database.types.ts file exists and is valid', () => {
    // database.types.ts is a type-only file generated by Supabase CLI
    // It exports the Database type used at compile-time
    // This test verifies the file exists in the project
    const fs = require('fs');
    const path = require('path');
    const filePath = path.resolve(__dirname, '../database.types.ts');
    expect(fs.existsSync(filePath)).toBe(true);
    
    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain('Database');
    expect(content).toContain('Tables');
  });
});
